language: php

cache:
  directories:
    - node_modules

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - npm i -g npm
  - npm i -g grunt-cli
  - travis_retry npm i
  - travis_retry composer install

script:
  - grunt ci
